# -*- coding: utf-8 -*-
"""incentive-discomfort-PAR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RQksJJzQD95R-zRyM-ozMc800MC_E8zi
"""

import matplotlib.pyplot as plt

# Configure fonts and sizes
plt.rcParams.update({
    'font.size': 18,
    'axes.labelsize': 18,
    'xtick.labelsize': 16,
    'ytick.labelsize': 16,
    'legend.fontsize': 16,
    'legend.title_fontsize': 18
})

# Data for plotting
methods = ['Previous Approach', 'Proposed Approach']
values = [94.15, 16.33]
# More vibrant colors
colors = ['steelblue', 'coral']

# Create bar chart with thinner bars
plt.figure()
plt.bar(methods, values, color=colors, width=0.4)

# Labels
plt.xlabel('Method')
plt.ylabel('EU Incentive (¢)')
plt.grid(False)

# No annotations on bars

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

# Configure fonts and sizes
plt.rcParams.update({
    'font.size': 18,
    'axes.labelsize': 18,
    'xtick.labelsize': 16,
    'ytick.labelsize': 16,
    'legend.fontsize': 16,
    'legend.title_fontsize': 18
})

# Data for CU discomfort
methods = ['Previous Approach', 'Proposed Approach']
discomfort_values = [3.1, 1.15]
colors = ['steelblue', 'coral']

# Create bar chart with thinner bars
plt.figure()
plt.bar(methods, discomfort_values, color=colors, width=0.4)

# Labels
plt.xlabel('Method')
plt.ylabel('EU Discomfort (¢)')
plt.grid(False)

# No annotations on bars

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

methods = ['No DR', 'Previous IBDR', 'Proposed IBDR']
peak = [16.05, 12.51, 8.3]
mean = [6.01, 4.76, 5.54]
par = [2.67, 2.63, 1.5]
colors = ['steelblue','coral','mediumseagreen']

fig, axes = plt.subplots(1, 3, figsize=(12,4))

# Peak load
axes[0].bar(methods, peak, color=colors, width=0.6)
axes[0].set_title('Peak Load (kW)')
axes[0].set_xticklabels(methods, rotation=45, ha='right')

# Mean load
axes[1].bar(methods, mean, color=colors, width=0.6)
axes[1].set_title('Mean Load (kW)')
axes[1].set_xticklabels([])  # می‌تونی تیک‌ها رو پنهان کنی

# PAR
axes[2].bar(methods, par, color=colors, width=0.6)
axes[2].set_title('PAR')
axes[2].set_xticklabels([])

for ax in axes:
    ax.grid(False)

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
from matplotlib.ticker import AutoLocator

# Configure fonts and sizes
plt.rcParams.update({
    'font.size': 16,
    'axes.titlesize': 18,
    'axes.labelsize': 16,
    'xtick.labelsize': 14,
    'ytick.labelsize': 14
})

# Data for plotting
methods = ['No DR', 'EBDR', 'CCRL-DR']
peak = [16.05, 12.51, 8.3]
mean = [6.01, 4.76, 5.54]
par = [2.67, 2.63, 1.5]
# Colors: green, blue, orange
colors = ['mediumseagreen', 'steelblue', 'coral']

# Create subplots
fig, axes = plt.subplots(1, 3, figsize=(14, 5), sharey=False)

# Plot 1: Peak load
axes[0].bar(methods, peak, color=colors, width=0.6)
axes[0].set_title('Peak Load')
axes[0].set_ylabel('kW')
axes[0].yaxis.set_major_locator(AutoLocator())
axes[0].tick_params(axis='x', rotation=30)

# Plot 2: Mean load
axes[1].bar(methods, mean, color=colors, width=0.6)
axes[1].set_title('Mean Load')
axes[1].yaxis.set_major_locator(AutoLocator())
axes[1].tick_params(axis='x', rotation=30)

# Plot 3: PAR
axes[2].bar(methods, par, color=colors, width=0.6)
axes[2].set_title('PAR')
axes[2].yaxis.set_major_locator(AutoLocator())
axes[2].tick_params(axis='x', rotation=30)

# Remove grids
for ax in axes:
    ax.grid(False)

plt.tight_layout()
plt.show()